### PR TITLE
Remove obsolete 2dcontext and offscreen-canvas configurations and test expectation

### PR DESCRIPTION
**Pull request by CYBAI**
`2dcontext` and `offscreen-canvas`are reorganized to `html/canvas/element` and `html/canvas/offscreen` in web-platform-tests/wpt#23070.

So, we will need to do these changes to fix the failures in servo/servo#26364.

---

By the way, I'm curious why the test expectation for `2dcontext` and `offscreen-canvas` are removed correctly in `metadata` folder but not in `metadata-layout-2020` 🤔 Do we miss something to run for `layout-2020` wpt sync?

### CODE REVIEW

**Comment by jdm** [comment]
The 2020 metadata changes are just duplicates of the 2013 changes by updating the results with the 2013 log file. we don't actually run the tests at all as part of the sync.

**Comment by CYBAI** [comment]
> The 2020 metadata changes are just duplicates of the 2013 changes by updating the results with the 2013 log file. we don't actually run the tests at all as part of the sync.

Ohh, I see!
Hmm, but does this mean, we have `deleted 2dcontext` changes for 2013 but it's not duplicated for 2020 👀?

**Comment by jdm** [comment]
Likely yes. It doesn't matter though because we don't run the 2dcontext tests in 2020. There are a lot of unnecessary test results because of the way we duplicate them.

**Comment by CYBAI** [comment]
Indeed! 👀 Thanks!

**Pull request merged**
